### ISSUE TITLE
How to sort the data using one variable and change the labels on the right to a different variable

### ISSUE THREAD

**Issue by taaanmay** [vasturiano/timelines-chart#103]
I want to sort the data using one variable. And instead of having that variable on the right, I want to have a different variable on the y-axis 

If I have different URLs and names of the website with their start date and end date,
I want to sort the data using URL (like www.github.com); but on the right-hand side, I want to have the name (like GitHub) instead of URL (www.github.com)

**Comment by vasturiano** [comment]
@taaanmay if you build a map between labels and sorting value, you can use it to do lookups inside the `sort` method, so you  can do more sophisticated comparisons between items that don't purely rely on the label.

**Comment by taaanmay** [comment]
@vasturiano Thank you very much for this. I will try it out.

**Comment by Arvind-puthucode** [comment]
hey taanmay can ya give an example u used for the sort() function as npm file only accepts one parameter
