### ISSUE TITLE
Custom tooltip content on hovering over the segment

### ISSUE THREAD

**Issue by amruthchundi** [vasturiano/timelines-chart#107]
Heyy,
I got a few doubts:
1. Unable to use the API method segmentTooltipContent as I want to customize what's shown on the block over hovering. Is it deprecated or can we still use it
2. Is there a way to override colors/styles on individual components like the hover block, segment colors, etc? 
3. Is there a way to add a label to the datemarker? 

Thank you :)

**Comment by vasturiano** [comment]
@amruthchundi thanks for reaching out.

1. Yes, `.segmentTooltipContent(segment => ...)` still works as described in the docs. You can use it to populate the content of each segment's tooltip. It receives the segment data object as argument.
2. In what regards the tooltips, you can include html/css in the content, f.e. ```.segmentTooltipContent(segment => `<div>${segment.name}</div>`)```. The segment's colors are controlled by the `zColorScale`.
3. I don't believe so.

**Comment by Abhilash-Koliwad** [comment]
Hi,

Even I am unable to use the API **.segmentTooltipContent(segment => ...)**. The method is not showing up on the TimelinesChart() instance, (example below)

      TimelinesChart()
        .zQualitative(true)
        .enableOverview(false)
        .maxLineHeight(40)
        .width(this.maxChartWidth())
        .onSegmentClick(this.onSegmentClick)
        .//_not able to add segmentTooltipContent here_
        
Will you please advise here @vasturiano,
Thankyou in advance :))

**Comment by vasturiano** [comment]
The attribute was missing from the typescript spec, that's likely why it wasn't showing up on your IDE. I've now added it, so it should fix your issue.
