### ISSUE TITLE
Series segments not being created on firefox

### ISSUE THREAD

**Issue by IRISHMAN04** [vasturiano/timelines-chart#135]
As title says, the series-segment rects work on chrome and edge, but not on firefox. 
Here are some example generated html with the linear gradient, axises and legendG removed, as they are the same on both browsers:
Chrome
```
<svg width="1920" height="106">
  <g transform="translate(200,26)">
    <rect class="series-group" x="0" y="0" height="50" style="fill: url('#areaGradient8117')" width="1620">
      <title>click-drag to zoom in</title>
    </rect>
    <rect class="series-segment" rx="1" ry="1" x="300.6275140788415" y="27.5" width="563.0430410297666" height="20" style="fill: rgb(255, 85, 114); fill-opacity: 0.8"></rect>
    <rect class="series-segment" rx="1" ry="1" x="25.631536604987932" y="2.5" width="1011.377715205149" height="20" style="fill: rgb(255, 85, 114); fill-opacity: 0.8"></rect>
  </g>
  <line class="x-axis-date-marker" style="display: none"></line>
  <text class="reset-zoom-btn" x="1803.8" y="20.8" style="text-anchor: end; font-size: 11px; opacity: 0.6">
    Reset Zoom
  </text>
</svg>
```
Firefox:
```
<svg width="1625" height="106">
  <g transform="translate(200,26)">
    <rect class="series-group" x="0" y="0" height="50" style="fill: url('#areaGradient5599')" width="1325">
      <title>click-drag to zoom in</title>
    </rect>
  </g>
  <line class="x-axis-date-marker" style="display: none"></line>
  <text class="reset-zoom-btn" style="text-anchor: end; font-size: 11px; opacity: 0.6" x="1511.75" y="20.8">
    Reset Zoom
  </text>
</svg>

```

**Comment by vasturiano** [comment]
@IRISHMAN04 thanks for reaching out.

I've just tried [this example](https://vasturiano.github.io/timelines-chart/example/categorical/) on the latest version of Firefox, and seems to render correctly.

Do you see your issue happening with the above example?

**Comment by IRISHMAN04** [comment]
Hmm. The example works just fine. I'll close the issue then and figure out why mine isn't working by myself, and post here if I figure it out.

**Comment by IRISHMAN04** [comment]
Ok so I figured it out. For some reason I was using US date format for my data, even though yours was using iso format. Changing it to iso format fixed the problem. I guess chrome and edge (both chromium) were able to understand the date format, but firefox wasn't?
