### ISSUE TITLE
Coloring individual (overlappign) segments

### ISSUE THREAD

**Issue by IRISHMAN04** [vasturiano/timelines-chart#137]
Some of the data I am displaying overlaps with each other, and I want to change the color for those segments without changing the category. The C# code that I have written that generates my dataset out of a csv file is able to identify which segments are overlapping before the data is put into the chart, but I can't think of a neat way to set the colors after being added to the chart. Is it possible to access a segment list on the chart object? The hacky fix would be that I iterate over all the rects until I find two that are overlapping, but I would like to use the data that I already have on it, because I already known exactly which segments need to change color, just not how to locate the related svg rect object.

**Comment by vasturiano** [comment]
I'd recommend to pre-process your data and turn the sub-segments that overlap into new segments (and subtract them for the original ones) so that you can style/categorize them separately. That will also have the advantage of not having overlapping elements in the SVG.

**Comment by IRISHMAN04** [comment]
That's an amazing idea, I'll get onto that, thanks!
