### ISSUE TITLE
Minimum segment width

### ISSUE THREAD

**Issue by ipi-applikationsbetrieb** [vasturiano/timelines-chart#147]
Thanks for this fantastic library

We are using it to show automated processes which may have a very short lifetime (seconds) or a very long lifetime (days or even months).
The very short ones are almost invisible on the chart at full zoom, they are represented by a narrow line of only one pixel. If they are very close to the border they are very hard to find. 
Would it be possible to have something like a configurable minimum width for a segment (in pixels) so that the short segments are visible?
![grafik](https://github.com/user-attachments/assets/fb189511-dfd7-40ee-99a3-f4349c6a57ea)

Thanks!

**Comment by vasturiano** [comment]
@ipi-applikationsbetrieb thanks for reaching out and sorry for the delay in answering here.

I've just added a new method `minSegmentWidth(<px>)` which allows you to do exactly what you describe. The default is set to 1px, as it already was the case.

**Comment by ipi-applikationsbetrieb** [comment]
wow, thanks for the update!
