### ISSUE TITLE
Add library to HTML in local machine.

### ISSUE THREAD

**Issue by wanaideed** [vasturiano/timelines-chart#15]
I download your file project with include folder src and insert a folder has ::-

- comparison.js
- index.js
- timelines.css
-timelines.js
- time-overview.js

I try add your library like this ,
<script src="../timeline/src/timeline.js"></script> but got problem.
please advise me,my website running in local environment.

**Comment by vasturiano** [comment]
Hi @wanaideed, if you want to load the lib directly via script tag you have to build it first: `npm run build`, and then import from the `dist` directory, not `src`. Like this:
`<script src='../../dist/timelines-chart.js'>` 

Alternatively, I would recommend loading the script directly from the unpkg cdn:
`<script src='//unpkg.com/timelines-chart'></script>`

**Comment by wanaideed** [comment]
Thanks @vasturiano .It's help me.
I have one question, this timeline support bullet point with single date data. as attchment.
![capture](https://user-images.githubusercontent.com/20812415/38192802-50278b22-36a1-11e8-9926-d25e9b8faacc.PNG)

**Comment by vasturiano** [comment]
@wanaideed each time segment should be a time range with `[<start>, <end>]` so one way to simulate the time makers you're referring to is to just define a short time period for your data point.
