### ISSUE TITLE
Extending project for personal use

### ISSUE THREAD

**Issue by smadan17** [vasturiano/timelines-chart#17]
Hi, 
I am using your tool for a project and was wondering whats the best way to import the files so I can extend the api that you have built.

**Comment by smadan17** [comment]
also what is the difference between timelines.js and timelines-chart.js

**Comment by vasturiano** [comment]
@smadan17 you can always fork the repo if you wish to extend it with functionality very specific to your use case. However, if you think your extensions may have a more generic application, you can open a PR or register a feature request in issues, so others may also take advantage of it.

There is no `timelines-chart.js` source file, only `timelines.js`. If you're referring to the generated file in the `/dist` folder, that is the transpiled/built package file to `UMD` using `rollup`. That's how applications can use this module as a dependency.

**Comment by smadan17** [comment]
@vasturiano thank you so much! 
I do have a question. Is there a way currently to set the ticks on the chart using the current api?

**Comment by vasturiano** [comment]
@smadan17 you can use `.xTickFormat([function])`.
