### ISSUE TITLE
Getting Error: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by Royalxm** [vasturiano/timelines-chart#19]
hello 

i get Getting Error: Object doesn't support property or method 'assign'

file: timelines-chart.js, line : 2, col: 3931

n=Object.assign({},e instanceof Function?e():e,{initialised:!1});

i see http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign

Browser compatibility :
IE11 :-1: 
EDGE :+1:

**Comment by vasturiano** [comment]
@Royalxm thanks for reaching out. Yes, the library is not well supported in legacy browsers like IE11.
