### ISSUE TITLE
Tooltips not displaying

### ISSUE THREAD

**Issue by theresagao** [vasturiano/timelines-chart#2]
When I mouse over any part of the graph and change direction, I get the following error.

```
Uncaught TypeError: Cannot read property 'target' of null
    at getScreenBBox (build.js:115507)
    at SVGRectElement.direction_w (build.js:115429)
    at SVGRectElement.tip.show (build.js:115288)
    at SVGRectElement.<anonymous> (build.js:106161)
getScreenBBox @ build.js:115507
direction_w @ build.js:115429
tip.show @ build.js:115288
(anonymous) @ build.js:106161
```

The tooltips are also not displayed, even though they are created and do load in the DOM.

**Comment by vasturiano** [comment]
Thanks for the report @theresagao. Are you able to reproduce the issue on this demo page?https://bl.ocks.org/vasturiano/raw/ded69192b8269a78d2d97e24211e64e0/

If yes, please let me know which browser version you're using when seeing the error.
If not, is there an example online of your component usage that I can look into?
