### ISSUE TITLE
Trying to get hosted library

### ISSUE THREAD

**Issue by iandewancker** [vasturiano/timelines-chart#27]
Hey there I'm trying to hit `https://unpkg.com/timelines-chart@2.6.8/index.js` but seeing 
```
Cannot find "/index.js" in timelines-chart@2.6.8
```
Is that just something weird with the unpkg hosting?

**Comment by vasturiano** [comment]
@iandewancker yes, there's some issues with `unpkg` right now: https://github.com/unpkg/unpkg.com/issues/156

**Comment by iandewancker** [comment]
Cool thanks for letting me know.  Timelines great library by the way, super useful!
