### ISSUE TITLE
Is there any way to put the timeline brush at the top instead of the bottom?

### ISSUE THREAD

**Issue by alexbfree** [vasturiano/timelines-chart#34]

**Comment by vasturiano** [comment]
I'm afraid not currently, no. At least not out of the box. Of course you can always build your own custom Overview area, and interact with the main chart via `zoomX` and `onZoom` calls.

**Comment by alexbfree** [comment]
ok thanks. i wonder if there is some way to get a handle to it and then "move" it to a different part of the page....

**Comment by alexbfree** [comment]
> you can always build your own custom Overview area, and interact with the main chart via `zoomX` and `onZoom` calls.
How would you programmatically trigger the reducing of the "active window" (as opposed to whole extent of grey bar) - like when you drag the blue bar in from the edge? (this same question will answer #32 as well!)

**Comment by vasturiano** [comment]
@alexbfree, as mentioned in #32, just update the value of `zoomX`.
