### ISSUE TITLE
Not able to increase maxLineHeight.

### ISSUE THREAD

**Issue by Chatcola** [vasturiano/timelines-chart#35]
Hi, thanks for this great chart.

I want to increase height of my elements. Increasing value of maxLineHeight change nothing.

But reducing the size of maxLineHeight under 12 px (default) reduce height of my elements.

**Comment by vasturiano** [comment]
@Chatcola you can just increase the `height` of the whole chart, using `maxHeight`. The segments height will adjust to fill the vertical space.

**Comment by Chatcola** [comment]
Indeed thanks for reply, zoom looks better.

![2](https://user-images.githubusercontent.com/25823356/52112439-ce0b0a00-2606-11e9-9793-edc15b3bcccc.PNG)

Still a bit messy with hudge amount of data, but give a nice preview.
