### ISSUE TITLE
Increase height

### ISSUE THREAD

**Issue by foreveRush** [vasturiano/timelines-chart#4]
Hi! How can I increase a height of each element? I have only one group and two labels. They look tiny. Maybe I can use some key to improve it?

**Comment by vasturiano** [comment]
@foreveRush thanks for reaching out. 
I've just published a new version (`2.2.0`) which exposes a property `maxLineHeight`, set to `12px` by default. You can increase that value to get taller lines.
The other height restriction is the `maxHeight` which is set to `640px` by default. You can play with those two values to get the configuration that you want.
