### ISSUE TITLE
Black gradient

### ISSUE THREAD

**Issue by marker4321** [vasturiano/timelines-chart#40]
I would like to change the gradient in the graph from a "white to light gray" to "black to dark gray". How do I make the change? I tried to change the colorScale in gradient, but that did not make any changes. Thanks.

**Comment by vasturiano** [comment]
@marker4321 thanks for reaching out. I'm afraid that's not currently customizable. The colors are hard-coded in the component here: https://github.com/vasturiano/timelines-chart/blob/master/src/timelines.js#L303.
