### ISSUE TITLE
Bootstrap responsible width.

### ISSUE THREAD

**Issue by curiousteam** [vasturiano/timelines-chart#41]
Hi,

I appreciate your work. You made a very nice package. I have searched in google and found only this package as my solution. I am using your package on my client's project. Your package helped me to earn $200 from the project. I really very very much appreciated the work.

Only one request to you, how we can make the width like bootstrap responsible columns. I know we can set the width by doing something like below:

`TimelinesChart()`
`.data(data)`
`.width($('#hour-chart').width())`

But using this method, width gets an overflow when the window is resized. Besides, It does not show correctly in mobile devices. Do you have a solution to handle this?

I hope you will keep up working on good things.

Thanks and Regards,
Rubel

**Comment by vasturiano** [comment]
@curiousteam thanks for your support and glad the lib is useful.
To make the chart responsive you need to add event handlers for window resize externally to this lib, and call `.width()` programatically. There's a few js modules out there hat can help you with this.
