### ISSUE TITLE
Customize text-size and pop-up window location

### ISSUE THREAD

**Issue by Foxtra** [vasturiano/timelines-chart#44]
I work with webOS application for TV and it has a big screen. 
Is it possible to customize text-size for labels, values in popup windows and text for categories (above the chart)? and also "Reset Zoom" button is veeery small :)
Also it would be cool for me to customize the popup window location, because you know the cursor on the TV is very large and it just covers the text in pop-up window :D
So I would like to display information for example above the cursor (selected time segment).

**Comment by vasturiano** [comment]
@Foxtra you can try to apply your own styling by overriding/extending the CSS rules found in this file: https://github.com/vasturiano/timelines-chart/blob/master/src/timelines.css
