### ISSUE TITLE
The timeline brush isn't usable on touchscreens

### ISSUE THREAD

**Issue by ChristophRuckstetter** [vasturiano/timelines-chart#48]
On touchscreens it's extremely hard to grab the edges of the timeline brush for changing the zoom level.

**Comment by vasturiano** [comment]
Thanks for the report @ChristophRuckstetter . I've increased the brush handle sizes so the interaction should be a bit easier now.

**Comment by ChristophRuckstetter** [comment]
Thank you for the fast fix. It works great now.
