### ISSUE TITLE
Is there any possible to track event on legend?

### ISSUE THREAD

**Issue by tpps88206** [vasturiano/timelines-chart#50]
Is there any possible to track event on legend?

For user who want to watch all element or bar which legend they choose.

For example, user want to highlight all of element in the chart which is the first legend.

I try to set the mouse event on the legend but it didn't work.

**Comment by vasturiano** [comment]
@tpps88206 thanks for reaching out. 

There is currently no functionality to handle legend click events. For this, I'd recommend building your own legend externally that lets you do click toggles or any other interactions you may need.

**Comment by tpps88206** [comment]
@vasturiano  Very thanks for your respond.

I will start to try your suggestion.
