### ISSUE TITLE
Using geologic time ranges

### ISSUE THREAD

**Issue by mickdee** [vasturiano/timelines-chart#51]
I'm having some difficulty using time ranges not formatted as dates. For example, dates in this case are formatted as integers that refer to millions of years ago. The x-axis would be optimal fixed for a specific duration (4600 to 0, for example) with 'date' range bars that are simple integers.

It looks to me like even the custom time format chart still requires data to be formatted as date/time, but is there a workaround for this use case? Cheers!

**Comment by vasturiano** [comment]
@mickdee thanks for reaching out. You can look into this example, for custom time formats:
http://vasturiano.github.io/timelines-chart/example/custom-time-format/
[source](https://github.com/vasturiano/timelines-chart/blob/master/example/custom-time-format/index.html)

Basically you can set the numbers in your dates to represent conceptually anything numeric, like millions of years for example. Then use `timeFormat` to display them as numbers (`%Q`), or any other format that you wish.
