### ISSUE TITLE
Cannot set Zoon out

### ISSUE THREAD

**Issue by goodguy000** [vasturiano/timelines-chart#54]
Thanks admin for your awesome project.
I tried to config zoom in and zoom out button, but we cannot set the API for that.
I create a button to click zoom out (reset zoom will back to initial view), we want click zoom out to back to previous zoom, not the initial zoom.
Any one have suggestion for that.
Thanks.

**Comment by vasturiano** [comment]
@goodguy000 you can use the methods `onZoom()`, `zoomX()` and `zoomY()` to implement that functionality.
