### ISSUE TITLE
"TypeError: Cannot read property 'timeRange' of undefined" in parseData

### ISSUE THREAD

**Issue by max-su** [vasturiano/timelines-chart#56]
The current parseData function for data throws an error when the first timeseries doesn't have any events: "TypeError: Cannot read property 'timeRange' of undefined"

Attached is documentation of the error and a suggested fix I have for PR review.
https://codepen.io/lilaclapras/pen/rNBKyBv

**Comment by vasturiano** [comment]
Thanks for the bug report @max-su! This is now fixed in `v2.8.3`.
I'll also close the PR since it's not applicable any longer.
