### ISSUE TITLE
Time difference

### ISSUE THREAD

**Issue by foreveRush** [vasturiano/timelines-chart#6]
I have next code:
```
let testData = [
       {
           group: "Audio",
           data: [
               {
                   label: "test",
                   data: [
                       {
                           timeRange: ["2016-12-15T18:00:20Z", "2016-12-15T18:01:29Z"],
                           val: "TEST"
                       },
                       {
                           timeRange: ["2016-12-15T18:03:29Z", "2016-12-15T18:05:29Z"],
                           val: "TEST"
                       }
                   ]
               }
          ]
       }
    ];

chart
     .data(testData)
     .width(width)
     .maxHeight(height)
     .(document.getElementById("test"));
```

And my chart looks  like:
![2017-10-18 14-37-57](https://user-images.githubusercontent.com/19690587/31716872-5c0e7d5e-b412-11e7-9017-25ee09d74ab6.png)

I think the problem is in UTC format, but how can I fix it?
Thanks.

**Comment by vasturiano** [comment]
Yes, this was a bug related to the timezone discrepancy. This has also been fixed in `v2.3.0`. 
There's a new method called `useUtc(<boolean>)` which can be used to set whether the timestamps everywhere in the chart are shown in UTC or local time.
Thanks for reporting the issue!
