### ISSUE TITLE
Can we filter by color ? 

### ISSUE THREAD

**Issue by shaimaaashraf** [vasturiano/timelines-chart#60]
Hi, I want to filter by selecting the colors of categories too, is it possible?

**Comment by vasturiano** [comment]
@shaimaaashraf you filter the data that is input to the chart, by any criteria that you'd like. Just call `.data(<your filtered dataset>)` when you'd like to update the chart with a new dataset.

**Comment by shaimaaashraf** [comment]
Thank you 👍
