### ISSUE TITLE
get specific group label

### ISSUE THREAD

**Issue by foreveRush** [vasturiano/timelines-chart#7]
Hi, I use `onLabelClick` callback:

```
onLabelClick(name) => {
   ....
}

chart
     ...
     .onLabelClick(this.onLabelClick);
```

I have few different groups with same labels' names. When I get some label name, I also need to know label group name.

Is there some way to get group also?

**Comment by vasturiano** [comment]
@foreveRush good point, thanks for reporting. There's a new version (`2.4.0`) which will include both the label and the group `onLabelClick(label, group)` if clicking on a label, and just the group if the label is a group `onLabelClick(group)`.
