### ISSUE TITLE
Too much ticks on small widths

### ISSUE THREAD

**Issue by ChristophRuckstetter** [vasturiano/timelines-chart#72]
Hi,

on small widths, there are too much ticks visible on the x-axis and the overview so they overlap.

See here for a screenshot: https://i.imgur.com/Z80Q57C.jpg

**Comment by vasturiano** [comment]
@ChristophRuckstetter thanks for reaching out.

Do you observe that also on the provided example: http://vasturiano.github.io/timelines-chart/example/categorical/ ?

If not, are you overriding any of the `timeFormat` or `xTickFormat` values?

**Comment by ChristophRuckstetter** [comment]
yes, the same thing happens on the example with my mobile phone and on a browser with a really small window width.

On my case, i am overwriting the xTickFormat values.

**Comment by vasturiano** [comment]
@ChristophRuckstetter thanks for reporting. This should be fixed in the latest version (`2.8.5`). 👍
