### ISSUE TITLE
TypeScript error TS2456: Type alias circularly references itself

### ISSUE THREAD

**Issue by qanh96** [vasturiano/timelines-chart#80]
Thanks for the wonderful work.
I'm having a problem when using the version 2.10.0 with Angular. The version 2.8.6 (without TS type def file) works fine.
- Paket Version
  - Angular-compiler:  8.2.3
  - Typescript: 3.5.3
  - timeline-chart from NPM: 2.10.0

- Terminal Error Info
```shell
ERROR in node_modules/timelines-chart/dist/timelines-chart.d.ts:109:6 - error TS2456: Type alias 'TimelinesChartInstance' circularly references itself.rtInstance' circularly references itself.

109 type TimelinesChartInstance = TimelinesChartGenericInstance<TimelinesChartInstance>;
```

**Comment by vasturiano** [comment]
@qanh96 you should update TS to at least `3.7`. https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/#more-recursive-type-aliases
