### ISSUE TITLE
Milliseconds in tooltip?

### ISSUE THREAD

**Issue by keithrz** [vasturiano/timelines-chart#9]
Great tool!  Thank you for making it!

Is there a way to show milliseconds in the From & To values for each tooltip?

**Comment by vasturiano** [comment]
@keithrz I've just added a property `timeFormat` in `v2.5.0` that lets you specify any custom timestamp format. So, if you want to include milliseconds, something like:
```
Chart.timeFormat('%Y-%m-%d %-I:%M:%S:%L %p)
```

Hopefully this helps your case.

**Comment by keithrz** [comment]
It did, indeed!  Thank you for the prompt reply, @vasturiano !!
