### ISSUE TITLE
customize the height of the bars

### ISSUE THREAD

**Issue by progressify** [vasturiano/timelines-chart#98]
How I can increment the height of the report bars?
there is a method or a CSS rule to override?

here a detail of my project, I want to increment the height of the bars from at least 2x

![image](https://user-images.githubusercontent.com/11472632/113896927-aefdf900-97ca-11eb-95aa-1d4c750d0e47.png)

**Comment by vasturiano** [comment]
@progressify there are 2 props that let you control this `maxHeight` and `maxLineHeight`. Have you tried those?

**Comment by progressify** [comment]
`maxLineHeight` is the method for me! thank you!
Yesterday I have tried `maxHeight` and `maxLineHeight` together, and that is the reason why I have a weird visualization.

**Comment by ryangriggs** [comment]
Is it possible to change the heights of bars in different groups?

**Comment by vasturiano** [comment]
@ryangriggs you can define the height of all the lines as a whole, but not individually per group/line. They need to be all the same for good space optimization.
